### ISSUE TITLE
I can write my workflow/pipeline in Snakemake instead of DVC

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#108]
Not sure the relative importance here. If we're providing a nice easy GUI maybe it doesn't even matter. It just matters that we can rerun it and steps get cached.

One thing I've noticed about Snakemake projects is they involve lots of different commands. I'm not sure if they are automatically run by default. This seems like sort of a bad pattern.

Maybe what we should do is compile a `Snakefile` to `dvc.yaml` in `calkit run`. Or we can simply create a single stage that runs Snakemake.

Started a project from the Snakemake tutorial here: https://calkit.io/petebachant/snakemake-tutorial

## Other ideas

- Add a command for converting and existing Snakemake project to Calkit -- adds environment, creates `dvc.yaml`, etc.
- Add project templates from [Snakemake workflows](https://snakemake.github.io/snakemake-workflow-catalog/)

## Working design

In `calkit.yaml`, we can declare our pipeline is (by default, we'd use DVC):

```yaml
pipeline:
  kind: snakemake
  environment: main # will need this to get the inputs and outputs with `snakemake -D`?
  split_rules: false # Use one stage
  stage_name: run-snakemake
  non_dvc_outs:
    - plots
    - calls
```
