### ISSUE TITLE
I can add/view videos for my project

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#14]
Want to be able to upload, view, and comment on them eventually, but this should be the bare minimum. Could provide a URL, e.g., from YouTube, where we can simply embed. In the future we can enable uploading and storing videos in DVC.

In `calkit.yaml`:

```yaml
videos:
  - url: https://youtube.com/...
    title: This is my video
  - path: videos/my-video.mp4
    title: This is the second video
```

The web app should provide a `url` for the videos saved in Git or DVC.
