### ISSUE TITLE
It's kind of a pain to need to define the DVC stage for a Calkit object in order to view the file

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#152]
Possible solutions:
1. Don't require the stage. Just look in `dvc.lock` for any outputs and get them from storage per MD5 hash.
2. Somehow automate the creation of the objects in `calkit.yaml`. This could happen in `dvc.yaml` with something like:
```yaml
stages:
  make-figure:
    cmd: calkit figure python scripts/plot-thing.py --title sup --desc lol --stage make-figure
```
3. Or we could use the DVC metadata to build `calkit.yaml` like `calkit detect`. This should be an idempotent command.
```yaml
stages:
  make-figure:
    cmd: python scripts/plot-thing.py
    outs:
      - figures/thing.png
    meta:
      calkit:
        type: figure
        title: This is the title
        description: This is the description.
```
