### ISSUE TITLE
I can easily bundle up all of my materials as supplementary resources so that it's faster to submit my paper

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#22]
Basically, click to archive on Figshare or Zenodo and import into references so it can be cited in the paper or whatever. Should probably do some research on current journal requirements.

Another use case is perhaps right after ideation, then right after a preliminary plan is in place.

Imagine we see a button next to an object that could be archived. Or maybe we see when one has been archived but is now out of date.

Make it easy to cite this in the paper?

Create/update [`CITATION.cff`](https://github.com/posit-dev/great-tables/blob/main/CITATION.cff) file when creating a project release?

How to make people feel okay about submitting paper with data published?

Automatically put placeholder citation in the paper?

We do want paper readers to get back to the project, however, so they can reuse some of what was created.

Should also be able to see a list of archived artifacts or "depositions" for a given project. Maybe just call them releases. You can release the project bundled up. You can release a dataset, a figure, whatever. Probably easiest to just release the entire project though.

Automatically adds to references?

Related to #26 

## Project releases

```sh
calkit config set zenodo_token dkfjhwr349u23wefuysih3iu4hiwushdfisuh
calkit new release . --to zenodo --add-to-refs --tag milestone-0
```

```yaml
# calkit.yaml
# These are top level releases of the project itself
# We track the MD5 hashes of any DVC-tracked files so we can go
# to the release instead of Calkit cloud storage to fetch files
# in the DVC push/pull endpoints
releases:
  - doi: 10.2339309df
    url: https://zenodo.org...
    tag: milestone-0
    github_url: ?
    md5_hashes:  # Maybe put these in `.calkit/releases/project/10.2343434.yaml`
    # The release details can also track the state of the upload
```

## Artifact releases

For publications, submitting to a journal constitutes a release. So does the publication. However, any artifact can be released whenever.

```yaml
publications:
  - path: paper/paper.pdf
    title: On the topic of the thing...
    releases:
      - doi: 10.232903
        url: https://somejournal.org
        md5: 239487dksjhdkjh5498rkjhrt
        notes: Submitted to some journal
        git_tag: milestone-1
      - doi: 10.2.arxiv.dkfjd
        url: https://arxiv.org/something
        notes: Posted on ArXiv. This is hard because they require source files.
```
