### ISSUE TITLE
Can see any DOIs (Figshare, Zenodo, et al.) for artifacts in a project, including the project itself

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#26]
Maybe a new section called archived artifacts or DOIs?

Could be "DOI registrations".

```yaml
dois:
  - path: "."
  - doi: 10.5444.figshare
  - url: https://figshare.com/434343
  - git_rev: 34fkjh43
  - published: true  # Is this just a reservation?
```

We probably should also support CITATION.cff files: https://citation-file-format.github.io/
