### ISSUE TITLE
I can read any tabular data through a defined interface

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#41]
A dataset can have an interface defined so we can use `calkit.read_data("data/some-data", source="someone/projectname", auto_import=True)`.

In a dataset definition, we could do something like:
```yaml
  interface:
    kind: py_package
    name: pyjhtdb
```

or

```yaml
  # Define an interface for how to read this data?
  read:
    - lang: python
    - func: pandas:read_hdf
    - args: data
    - kwargs: null
```
