### ISSUE TITLE
I want to be able to export a Plotly figure as JSON and view it on the web

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#45]
In `dvc.yaml`:

```yaml
stages:
  plot-thing:
    cmd: python scripts/make-my-plotly-figure.py
    deps:
      - scripts/make-my-plotly-figure.py
    outs:
      - figures/my-plotly-figure.json
    meta:
      calkit:
        type: figure
        title: My cool Plotly figure
        description: This figure was saved as JSON so it can be viewed interactively on the web.
```

Do we need some special notation to tell the front end that a JSON file is a Plotly figure? We can probably infer from the content if it has `data` and `layout` keys.
