### ISSUE TITLE
I can use Calkit for a project where data is collected continuously (ops?)

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#54]
For example, a wind farm.

The workflow would be something like

```yaml
stages:
  process-raw-data:
    deps:
      - data/raw  # Needs to be incremental, partitioned; data gets in here via API
    cmd: calkit transform data data/raw mymodule:some_func
    outs:
      - path: data/processed # A partitioned Iceberg table?
  plot-daily-power-curves:
    cmd: calkit plot mymodule:some_func
    deps:
      - data/processed
    outs:
      - figures/power-curves # Incremental
```

Ops can continuously run on whatever machine collects data, adding raw Parquet files into a folder that auto-increments file names or times of writing, they can be pushed to the cloud, then they can be processed by the pipeline somewhere else.
