### ISSUE TITLE
I can import another git repo or project for a references collection

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit-cloud#85]
Sort of what I used to do with my library repo.

```yaml
references:
  - path: library/library.bib
    submodule_path: library
    imported_from: https://github.com/petebachant/library.git
```

A user could define a global references collection and automatically add it as a submodule to new projects.
